namespace: refol
name: general
version: "0.0.3"
readme: README.md

authors:
  - "Francis Refol"

description: >
  General-purpose Ansible collection providing utility modules and Redmine
  automation helpers. Includes modules such as `consolidate_variable` for
  merging list-type variables across inventories, and `redmine_wiki_mirror`
  for mirroring Redmine wiki content into a local Git repository.

license:
  - MIT

tags:
  - ansible
  - general
  - inventory
  - variables
  - redmine
  - wiki
  - git
  - automation

dependencies: {}

repository: "https://github.com/t3knoid/refol.general"
documentation: README.md
issues: "https://github.com/t3knoid/refol.general/issues"
homepage: "https://github.com/t3knoid/refol.general"
